// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmUTNvvQNWT5fzjHLk_F2K3U1B12g9hBQ',
    appId: '1:940934180446:web:75801d7f6ee1ee87f38ecf',
    messagingSenderId: '940934180446',
    projectId: 'afsbot-6f20d',
    authDomain: 'afsbot-6f20d.firebaseapp.com',
    storageBucket: 'afsbot-6f20d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxKuzuAjt5BcmP48CZnB5_DopPDIXbU2A',
    appId: '1:940934180446:android:013427410ff6248ef38ecf',
    messagingSenderId: '940934180446',
    projectId: 'afsbot-6f20d',
    storageBucket: 'afsbot-6f20d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-P4cPJ_KzRA9nOBKlVUBcLm07M3Nod2o',
    appId: '1:940934180446:ios:d03dabda6deb7561f38ecf',
    messagingSenderId: '940934180446',
    projectId: 'afsbot-6f20d',
    storageBucket: 'afsbot-6f20d.appspot.com',
    iosBundleId: 'com.example.afsbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-P4cPJ_KzRA9nOBKlVUBcLm07M3Nod2o',
    appId: '1:940934180446:ios:077133f4948b94f9f38ecf',
    messagingSenderId: '940934180446',
    projectId: 'afsbot-6f20d',
    storageBucket: 'afsbot-6f20d.appspot.com',
    iosBundleId: 'com.example.afsbot.RunnerTests',
  );
}
